### ISSUE TITLE
Update to Gatsby 5

### ISSUE THREAD

**Issue by jonrutter** [jonrutter/v1#37]
Update site to [Gatsby 5](https://www.gatsbyjs.com/gatsby-5/).

[Migration guide](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/)

**Comment by rutterjt** [comment]
[Migrating to new MDX version](https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/#migrating-from-v3-to-v4)
