### ISSUE TITLE
Nav Redesign

### ISSUE THREAD

**Issue by jonrutter** [jonrutter/v1#60]
It might be better to redesign the nav bar to always be fixed to the top of the viewport. 

Although the disappearing nav bar helps create more vertical space for reading on small screens, it causes some issues:

1. It has the potential to be confusing or unpredictable for users who aren't used to it.
2. It impairs accessibility by working inconsistently when tabbing through the page: even when tabbing down, it unpredictably closes and opens.
3. The same happens when using intra-page links.
4. Sometimes the component fails to hide when scrolling down, depending on what element is focused, which can exacerbate confusion for some users.
5. Using a fixed nav bar would improve performance, since it wouldn't require a scroll event listener.
6. It would improve the page's time-to-interactive. Because the current setup requires using the DOM API, its first render must be deferred to the client, which causes a noticeable lag compared to the rest of the page.

**Comment by rutterjt** [comment]
As part of the redesign, could move the nav bar to a sidebar on larger screens. 

As an added bonus, if the blog post table of contents (#51) are added as a right-sidebar, moving the nav in a left-sidebar could create some visual balance.
